# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: oauth-apikey
spec:
  name: Secret Api Key For OAuth
  policies:
    - StrategyFullAccess
---
# OAUTH DASHBOARD
apiVersion: dashboard/v1
kind: Dashboard
metadata:
  name: oauth-dashboard
spec:
  name: OAuth Configurations
  icon: login
  components:
    - name: Google
      url: api:/fn-execute/load-google-oauth
      type: card
    - name: Facebook
      url: api:/fn-execute/load-facebook-oauth
      type: card
---
# FUNCTION OAUTH
apiVersion: function/v1
kind: Function
metadata:
  name: oauth-function
spec:
  title: OAuth
  description: All necessary methods to sign-in and sign-up users to the spica via OAuth. Current identity providers are Google and Facebook
  timeout: 2
  code: ./function/index.js
  runtime:
    name: Node
    language: Javascript
  environment:
    - name: OAUTH_APIKEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: oauth-apikey
  dependency:
    - name: "axios"
      version: latest
---
# TRIGGER - Load Google OAuth
apiVersion: function/v1
kind: Trigger
metadata:
  name: load-google-oauth-trigger
spec:
  name: loadGoogle
  func: oauth-function
  type: http
  httpOptions:
    method: Get
    path: /load-google-oauth
---
# TRIGGER - Upsert Google OAuth
apiVersion: function/v1
kind: Trigger
metadata:
  name: upsert-google-oauth-trigger
spec:
  name: upsertGoogle
  func: oauth-function
  type: http
  httpOptions:
    method: Post
    path: /upsert-google-oauth
---
# TRIGGER - Load Facebook OAuth
apiVersion: function/v1
kind: Trigger
metadata:
  name: load-facebook-oauth-trigger
spec:
  name: loadFacebook
  func: oauth-function
  type: http
  httpOptions:
    method: Get
    path: /load-facebook-oauth
---
# TRIGGER - Upsert Facebook OAuth
apiVersion: function/v1
kind: Trigger
metadata:
  name: upsert-facebook-oauth-trigger
spec:
  name: upsertFacebook
  func: oauth-function
  type: http
  httpOptions:
    method: Get
    path: /upsert-facebook-oauth